### ISSUE TITLE
Initial taskcat GitHub Action MVP

### ISSUE THREAD

**Issue by ShahradR** [ShahradR/action-taskcat#1]
Implement a minimum viable product, where the GitHub Action can run [taskcat](https://aws-quickstart.github.io/taskcat/) and deploy an AWS CloudFormation template to AWS.

Specifically, the features required in the MVP would be:

- [x] Get the taskcat prompt when running the GitHub action 
- [x] Read the `.taskcat.yml` file, located at the root of the repository
- [x] Allow access to the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
- [x] Deploy a CloudFormation template to AWS

**Comment by ShahradR** [comment]
By including a sample workflow under `.github/workflows/main.yaml`, we are able to simulate the action's execution using [act](https://github.com/nektos/act).

[![asciicast](https://asciinema.org/a/309152.svg)](https://asciinema.org/a/309152)

To run the action without pushing code to a repository, set `uses: ./` in the workflow definition, as shown below.

```yaml
---
on: [push]

jobs:
  taskcat:
    runs-on: ubuntu-latest
    name: Validate CloudFormation templates
    steps:
      - name: Run taskcat
        id: taskcat
        uses: ./
```

The file and folder structure used for the test above is shown below.
```
.
├── .gitattributes
├── .github
│   └── workflows
│       └── main.yaml
├── .gitignore
├── .pre-commit-config.yaml
├── .taskcat.yml
├── Dockerfile
├── LICENSE
├── README.md
├── action.yaml
├── commitlint.config.js
└── templates
    └── my-template.yaml
```

**Comment by ShahradR** [comment]
We currently aren't able to provision an AWS account for end-to-end testing (see #3). Since the remaining work in this MVP depends on taskcat's ability to connect to an AWS account and create CloudFormation resources, this issue is on hold until #3 is resolved.

**Comment by ShahradR** [comment]
The AWS account creation issue outlined in #3 has been resolved by adding the user to the Service Catalog portfolio. Additionally, I wrote a quick [gist](https://gist.github.com/ShahradR/ed092670cc57965cb5e3316d265ece16) around AWS Control Tower setup, for future reference.

**Comment by ShahradR** [comment]
Commit 27f8287 removes the `inputs` section of the `action.yaml` file, allowing the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables to be properly passed to the taskcat Docker container.

GitHub Action inputs are prefixed with `INPUT_`. For example, when passing the `AWS_ACCESS_KEY_ID`, it would appear to the container as `INPUT_AWS_ACCESS_KEY_ID`, which taskcat does not recognize.

By removing the `inputs` from the file, the environment variables are passed as-is, resolving the issue.

In the `.github/workflows/main.yaml` file that consumes the action, we also need to change how the credentials are passed in. The changes are highlighted below.

**Before change**
```yaml
---
on: [push]

jobs:
  taskcat:
    runs-on: ubuntu-latest
    name: taskcat
    steps:
      - name: taskcat
        id: taskcat
        uses: ./
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

```

**After change**
```yaml
---
on: [push]

jobs:
  taskcat:
    runs-on: ubuntu-latest
    name: taskcat
    steps:
      - name: Run taskcat
        id: taskcat
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

```
