### ISSUE TITLE
Directly use the taskcat/taskcat Docker container

### ISSUE THREAD

**Issue by ShahradR** [ShahradR/action-taskcat#20]
Eliminate the need for a local Dockerfile—we can directly use the [`taskcat/taskcat:latest`](https://hub.docker.com/r/taskcat/taskcat) container image on Docker Hub. Custom scripts can be executed without the need to define a `Dockerfile` by using the [`pre-entrypoint`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#pre-entrypoint) and [`post-entrypoint`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post-entrypoint).

**Comment by ShahradR** [comment]
Because both the `entrypoint` and `args` both expect lists, we can't call taskcat directly without a script to tokenize the string and create a `CMD` array for Docker to consume. While there is some string manipulation available from yaml when running the tests (not sure if it's provided by YAML itself, act, or if it's even available from GitHub Actions), it probably isn't enough to make it work without the need for a `Dockerfile` and an entrypoint script to split the command into tokens.

# Using the `.split()` function to return a list
A `.split()` function actually works against stings. Unfortunately, the array is cast back into a string when passed to the Docker container and taskcat still throws an error.

## `action.yaml`
```yaml
runs:
  using: docker
  image: docker://taskcat/taskcat:latest
  entrypoint:
    - taskcat
  args:
    - ${{ inputs.commands.split(" ") }}
```

## `.github/workflow`
```yaml
steps:
  - uses: actions/checkout@v2
  - name: taskcat
    uses: ./../../../../
    with:
      commands: test run
```

## act output
```
[main.yaml/taskcat] ⭐  Run taskcat
[main.yaml/taskcat]   🐳  docker run image=taskcat/taskcat:latest entrypoint=["taskcat"] cmd=["test,run"]
[main.yaml/taskcat]   |  _            _             _   
[main.yaml/taskcat]   | | |_ __ _ ___| | _____ __ _| |_ 
[main.yaml/taskcat]   | | __/ _` / __| |/ / __/ _` | __|
[main.yaml/taskcat]   | | || (_| \__ \   < (_| (_| | |_ 
[main.yaml/taskcat]   |  \__\__,_|___/_|\_\___\__,_|\__|
[main.yaml/taskcat]   |                                 
[main.yaml/taskcat]   | 
[main.yaml/taskcat]   | 
[main.yaml/taskcat]   | version 0.9.18
[main.yaml/taskcat]   | usage: taskcat [args] <command> [args] [subcommand] [args] 
[main.yaml/taskcat]   | taskcat: error: argument : invalid choice: 'test,run' (choose from 'delete', 'deploy', 'lint', 'list', 'package', 'test', 'update-ami', 'upload')
[main.yaml/taskcat]   ❌  Failure - taskcat
```

# Passing list values using the index
Because the `split()` function actually returns an array, we can get individual items by referencing its index. However, because we can't predict how many arguments will be passed, this is useless without the ability to iterate and dynamically build the `args` list.

## `action.yaml`
```yaml
runs:
  using: docker
  image: docker://taskcat/taskcat:latest
  entrypoint:
    - taskcat
  args:
    - ${{ inputs.commands.split(" ")[0] }}
```

## `.github/workflow`
```yaml
steps:
  - uses: actions/checkout@v2
  - name: taskcat
    uses: ./../../../../
    with:
      commands: test run
```

## act output
```
[main.yaml/taskcat] ⭐  Run taskcat
[main.yaml/taskcat]   🐳  docker run image=taskcat/taskcat:latest entrypoint=["taskcat"] cmd=["test"]
[main.yaml/taskcat]   |  _            _             _   
[main.yaml/taskcat]   | | |_ __ _ ___| | _____ __ _| |_ 
[main.yaml/taskcat]   | | __/ _` / __| |/ / __/ _` | __|
[main.yaml/taskcat]   | | || (_| \__ \   < (_| (_| | |_ 
[main.yaml/taskcat]   |  \__\__,_|___/_|\_\___\__,_|\__|
[main.yaml/taskcat]   |                                 
[main.yaml/taskcat]   | 
[main.yaml/taskcat]   | 
[main.yaml/taskcat]   | version 0.9.18
[main.yaml/taskcat]   | usage: taskcat [args] test [args] [subcommand] [args] 
[main.yaml/taskcat]   | taskcat [args] <command> [args] [subcommand] [args] test: error: the following arguments are required: 
[main.yaml/taskcat]   ❌  Failure - taskcat
```
